# $Id$

# Makefile to generate the MacPorts HTML guide pages.
# The ports 'docbook-xsl', 'docbook-xml' and 'libxslt' have to be installed.
# For the guide-dblatex target, the 'dblatex' port is also required.

# If your MacPorts isn't installed in /opt/local you have to change PREFIX
# here.

UNAME := $(shell uname)

# Prefix of the MacPorts installation.
PREFIX = /opt/local
ifeq ($(UNAME), Linux)
PREFIX = /usr
endif

# Command abstraction variables.
MKDIR    = /bin/mkdir
CP       = /bin/cp
RM       = /bin/rm
LN       = /bin/ln
ifeq ($(UNAME), Linux)
SED      = /bin/sed
REINPLACE = $(SED) -i -r
else
SED      = /usr/bin/sed
REINPLACE = $(SED) -i '' -E
endif
TCLSH    = /usr/bin/tclsh
XSLTPROC = $(PREFIX)/bin/xsltproc
XMLLINT  = $(PREFIX)/bin/xmllint
DBLATEX  = $(PREFIX)/bin/dblatex

# Data directories.
GUIDE = guide
# Source directories.
GUIDE_SRC = $(GUIDE)/xml
# Result directories.
GUIDE_RESULT         = $(GUIDE)/html
GUIDE_RESULT_DBLATEX = $(GUIDE)/dblatex

# Path to the DocBook XSL files.
DOCBOOK         = $(PREFIX)/share/xsl/docbook-xsl
ifeq ($(UNAME), Linux)
DOCBOOK         = $(PREFIX)/share/xml/docbook/stylesheet/docbook-xsl
endif
GUIDE_XSL       = $(GUIDE)/resources/single-page.xsl
GUIDE_XSL_CHUNK = $(GUIDE)/resources/chunk.xsl

# DocBook HTML stylesheet for the guide.
STYLESHEET = docbook.css

# MacPorts versions
MACPORTS_RELEASED = 2.4 2.4.0 2.4.1 2.4.2
MACPORTS_NEXT     = 2.5 2.5.0 2.4.3

gen_audience = $(subst $(eval) ,;,$1)
MACPORTS_RELEASED_AUDIENCE = $(call gen_audience,$(MACPORTS_RELEASED))
MACPORTS_NEXT_AUDIENCE = $(call gen_audience,$(MACPORTS_NEXT))

.PHONY: all guide guide-next guide-chunked guide-chunked-next guide-dblatex clean validate

all: guide guide-next guide-chunked guide-chunked-next

# Generate the HTML guide using DocBook from the XML sources
guide: GUIDE_OUTDIR= $(GUIDE_RESULT)
guide-next: GUIDE_OUTDIR = $(GUIDE_RESULT)/next
guide-chunked: GUIDE_OUTDIR = $(GUIDE_RESULT)/chunked
guide-chunked-next: GUIDE_OUTDIR = $(GUIDE_RESULT)/next/chunked
guide-chunked guide-chunked-next: GUIDE_XSL = $(GUIDE_XSL_CHUNK)

$(GUIDE)/resources/xsl:
ifeq ($(UNAME), Linux)
	$(LN) -sfn $(DOCBOOK) $(GUIDE)/resources/xsl
else
	$(LN) -sfh $(DOCBOOK) $(GUIDE)/resources/xsl
endif

guide guide-next guide-chunked guide-chunked-next:: $(GUIDE)/resources/xsl
	$(MKDIR) -p $(GUIDE_OUTDIR)
	$(CP) $(GUIDE)/resources/$(STYLESHEET) $(GUIDE_OUTDIR)/$(STYLESHEET)
	$(CP) $(GUIDE)/resources/images/* $(GUIDE_OUTDIR)/
	$(CP) $(GUIDE)/resources/*.js $(GUIDE_OUTDIR)/
	$(XSLTPROC) --xinclude \
	    --stringparam profile.audience \
	        "$(if $(filter %-next,$@),$(MACPORTS_NEXT_AUDIENCE),$(MACPORTS_RELEASED_AUDIENCE))" \
	    --output $(GUIDE_OUTDIR)/index.html \
	    $(GUIDE_XSL) $(GUIDE_SRC)/guide.xml
	# Convert all sections (h1-h9) to a link so it's easy to link to them.
	# If someone knows a better way to do this please change it.
	$(REINPLACE) \
	    's|(<h[0-9] [^>]*><a id="([^"]*)"></a>)([^<]*)(</h[0-9]>)|\1<a href="#\2">\3</a>\4|g' \
	    $(GUIDE_OUTDIR)/index.html

guide-chunked guide-chunked-next::
	# Add the table of contents to every chunked HTML file.
	# If someone knows a better way to do this please change it.
	$(TCLSH) toc-for-chunked.tcl $(GUIDE_OUTDIR)

# Generate the guide as a PDF.
guide-dblatex: SUFFIX = pdf
guide-dblatex: $(GUIDE)/resources/xsl
	$(MKDIR) -p $(GUIDE_RESULT_DBLATEX)
	$(XSLTPROC) --xinclude \
	    --stringparam profile.audience \
		"$(if $(filter %-next,$@),$(MACPORTS_NEXT_AUDIENCE),$(MACPORTS_RELEASED_AUDIENCE))" \
	    --output $(GUIDE_RESULT_DBLATEX)/guide.xml \
	     $(GUIDE)/resources/xsl/profiling/profile.xsl \
	     $(GUIDE_SRC)/guide.xml
	$(DBLATEX) \
		--fig-path="$(GUIDE)/resources/images" \
		--type="$(SUFFIX)" \
		--param='toc.section.depth=2' \
		--param='doc.section.depth=3' \
		--output="$(GUIDE_RESULT_DBLATEX)/macports-guide.$(SUFFIX)" \
		$(GUIDE_RESULT_DBLATEX)/guide.xml

# Remove all temporary files generated by guide:.
clean:
	$(RM) -f  $(GUIDE)/resources/xsl
	$(RM) -rf $(GUIDE_RESULT)
	$(RM) -rf $(GUIDE_RESULT_DBLATEX)
	$(RM) -f  guide.tmp.xml

# Validate the XML files for the guide.
validate:
	$(XMLLINT) --xinclude --loaddtd --postvalid --noout $(GUIDE_SRC)/guide.xml
