[[_reference.tcl_extensions]]
= Tcl Extensions & Useful Tcl Commands

A MacPorts Portfile is a Tcl script, so it may contain any arbitrary Tcl code you may learn about in a link:Tcl reference manual.
However, few authors will use arbitrary Tcl code; the vast majority will use a subset of Tcl commands and a number of Tcl extensions that are coded within MacPorts for performing the most common tasks needed for Portfiles.
The list below is a list of useful Tcl commands for Portfile development and Tcl extensions provided by MacPorts base.

file::
The standard Tcl `file` command can be used for a number of operations on files, such as moving, renaming, deleting, or creating directories, among others.
For a complete list, consult the link:Tcl
reference manual for the file command, or the Tcl file manpage in the [option]``n`` section of manpages on your machine using `man n file`

file copy::
Copy a file.

file rename::
Rename a file.

file delete [-force]::
Remove a file or (with [option]``-force``) a directory and its contents.

file mkdir::
Create a directory.
macros::
For the above operations provided by Tcl's `file` command, MacPorts provides the following shorthands.
These should be used in preference to the Tcl commands above, as they may work around certain bugs.

copy::
Shorthand for ``file copy``.

move::
Similar to `file rename` but correctly handles renames that only change the case of a file on a case-insensitive filesystem.

delete::
Shorthand for ``file delete -force``.

touch::
Mimics the BSD touch command.

ln::
Mimics the BSD ln command.
xinstall::
xinstall copies files and creates directories; it is intended to be compatible with install(1).

xinstall [-o [replaceable]``owner``] [-g [replaceable]``group``] [-m [replaceable]``mode``] [[replaceable]``file1 file2 ...``] [replaceable]``directory``::
Install the specified file(s) to a destination directory.

xinstall [-o [replaceable]``owner``] [-g [replaceable]``group``] [-m [replaceable]``mode``] [-W [replaceable]``dir``] [[replaceable]``file1 file2 ...``] [replaceable]``directory``::
Change to [option]``dir`` and install file(s) to a destination directory.

xinstall [-o [replaceable]``owner``] [-g [replaceable]``group``] [-m [replaceable]``mode``] {*}[glob [replaceable]``pattern``] [replaceable]``directory``::
Install the file(s) matching the glob pattern to a destination directory.
Note the use of the [option]``{*}`` operator to convert the list returned by `glob` into separate arguments to ``xinstall``.

xinstall -d [-o [replaceable]``owner``] [-g [replaceable]``group``] [-m [replaceable]``mode``] [replaceable]``directory``::
Create a directory including parent directories if necessary.
+
Defaults:

* owner -
* group -
* mode - [option]``0755``

+
Examples:
+


[source]
----
xinstall -m 640 ${worksrcpath}/README \
   ${destroot}${prefix}/share/doc/${name}
----
+

[source]
----
xinstall -m 640 -W ${worksrcpath}/doc README INSTALL COPY \
   ${destroot}${prefix}/share/doc/${name}
----
+

[source]
----
xinstall -m 640 {*}[glob ${worksrcpath}/doc/*] \
   ${destroot}${prefix}/share/doc/${name}
----
+

[source]
----
xinstall -d ${destroot}${prefix}/share/doc/${name}
----
strsed::
strsed can be used for string manipulations using regular expressions.
It supports a small subset of the commands known from sed(1).

strsed [replaceable]``string`` s/[replaceable]``regex``/[replaceable]``replacement``/ ::
Replaces the first instance of [replaceable]``regex`` with [replaceable]``replacement``.
Refer to re_format(7) for a definition of regular expression syntax.

strsed [replaceable]``string`` g/[replaceable]``regex``/[replaceable]``replacement``/ ::
The same as the previous format, except all instances of the pattern will be replaced, not only the first (mnemonic: 'g' is for global).
reinplace::
Allows text specified by a regular expression to be replaced by new text, in-place (the file will be updated itself, no need to place output into a new file and rename).
 reinplace [-locale [replaceable]``locale``] [-n] [-W [replaceable]``dir``] [--] [replaceable]``command``[replaceable]``file ...``::
Replace text given by the regular expression portion of the command with the replacement text, in all files specified.
+
Use -locale to set the locale.
The default locale is ``en_US.UTF-8``.
For example, `-locale C` will allow a non-UTF-8 file to be modified (which may otherwise give the error "sed: RE error: illegal byte sequence"), but only operating on ASCII characters.
If you need it to work on non-ASCII characters you need to set a locale with the correct charset for the file, e.g.
"en_US.ISO8859-1".
+
-n is passed to sed to suppress echoing result
+
-W to set a common working directory for multiple files
+
Use -E to use the extended regular expression style (see re_format(7) for a description of the basic and extended styles)
+
Use -- to end option processing and allow any further dashes not to be treated as options.
+
Examples:
+


[source]
----
reinplace -W ${worksrcpath} "s|/usr/local|${prefix}|g" configure setup.py
----
+

[source]
----
reinplace "s|@@PREFIX@@|${prefix}|g" ${worksrcpath}/Makefile
----
user/group::


adduser username [uxml:id=[replaceable]``uid``] [gxml:id=[replaceable]``gid``] [passwd=[replaceable]``passwd``] [realname=[replaceable]``realname``] [home=[replaceable]``home``] [shell=[replaceable]``shell``]::
Add a new local user to the system with the specified uid, gid, password, real name, home directory and login shell.

existsuser [replaceable]``username``::
Check if a local user exists.
Returns the uid for the given user, or 0 if the user wasn't found.
Checking for the root user is not supported because its uid is 0, and it will always exist anyway.

nextuid::
Returns the highest used uid plus one.

addgroup [replaceable]``group`` [gxml:id=[replaceable]``gid``] [passwd=[replaceable]``passwd``] [realname=[replaceable]``realname``] [users=[replaceable]``users``]::
Add a new local group to the system, with the specified gid, password, real name, and with a list of users as members.

existsgroup [replaceable]``group``::
Check if a local group exists and return the corresponding gid.
This can be used with adduser:
+


[source]
----
addgroup foo
adduser foo gxml:id=[existsgroup foo]
----

nextgid::
Returns the highest used gid plus one.
External program execution::
Use only when ....