[[_reference.livecheck]]
= Livecheck / Distcheck

Options livecheck and distcheck are especially useful for port maintainers, but others may also find this information valuable.

Livecheck checks to see if MacPorts can query the developer's download site to determine if a newer version of the software has become available since the port was installed.

livecheck.type::
Specify what kind of update check to perform.
+
Open source mirror site options are to use the project's latest file release from [option]``sourceforge`` or the project's `date_updated` XML tag for [option]``freecode``.
These options are automatically used if a matching [var]``${master_sites}`` URL is used.
+
Generic download site options are to specify a [option]``moddate`` (modification date of a URL resource), a [option]``regex`` (retrieve the version by applying a regex to a URL resource), [option]``regexm`` (retrieve the version by applying a multi-line regex to a URL resource), [option]``md5`` (compares the md5 sum of a URL resource) or [option]``none`` (no check).

* Default: [option]``sourceforge`` or [option]``googlecode`` if the [var]``${master_sites}`` is one of these, else [option]``freecode``.
* Values: [option]``freecode``[option]``sourceforge``[option]``googlecode``[option]``moddate``[option]``regex``[option]``regexm``[option]``md5``[option]``none``
* Examples:
+

[source]
----
livecheck.type     regex
livecheck.url       ${homepage}
livecheck.regex     "Generally Available (\\d+(?:\\.\\d+)*)"
----

livecheck.name::
Name of the project for live checks.
Is only used with freecode, sourceforge

* Default: [var]``${name}`` or the sourceforge, freecode project name if it can be guessed from [var]``${master_sites}``.
* Example:
+

[source]
----
livecheck.name      hibernate
----

livecheck.distname::
Name of the file release for sourceforge checks.
Use the name of the package release.
You may use this keyword without `livecheck.version` if you replace the version part of the name with "``(.*)``".

* Default: sourceforge: [var]``${livecheck.name}``
* Example:
+

[source]
----
livecheck.distname  faad2.src
----

livecheck.version::
Version of the project for a check; used for regex-based checks.

* Default: [var]``${version}``
* Example:
+

[source]
----
livecheck.version   ${name}-${version}
----

livecheck.url::
URL to query for a check.

* Default:
** [var]``${homepage}`` or the first hit among the following sites:
** `http://freecode.com/projects-xml/${livecheck.name}/${livecheck.name}.xml`
** `https://sourceforge.net/api/file/index/project-name/${livecheck.name}/rss`
** `https://code.google.com/p/${livecheck.name}/downloads/list`
* Example:
+

[source]
----
livecheck.url       https://ftp.gnu.org/gnu/bison/
----

livecheck.regex::
Regular expression to parse the resource for regex checks.
Be sure to use a regular expression grouping around the version component.
Also remember that square brackets need to be quoted because Tcl otherwise interprets them as a procedure call.

* Default: none
* Example:
+

[source]
----
livecheck.regex     4th-(\[a-z0-9.\]+)-unix${extract.suffix}
----
+

livecheck.md5::
md5 checksum to use for an md5 comparison.

* Default: none
* Example:
+

[source]
----
livecheck.md5       37e6a5b6516a680c7178b72021d3b706
----
Distcheck reports whether or not the distfile(s) specified in a Portfile are still available on the developer's download site.
Examples are given below.

distcheck.check::
This option can be used to disable distcheck.
It specifies what kind of check should be performed on distfiles: [option]``moddate`` (check if the Portfile is older than the distfile) or [option]``none`` (no check).

* Default: [option]``moddate``
* Example:
+

[source]
----
distcheck.check     none
----
